# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (every day at 03:00 am)
  schedule: [{cron: "0 3 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}

env:
  DESIRED_COMMIT_MESSAGE: Update github-metrics.svg - [Skip GitHub Action]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update metrics
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: kewldan
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Moscow
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories
          plugin_gists: yes
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_skipped: kewldan/SummerTimer
          plugin_languages_threshold: 0%
          plugin_stars: yes
          plugin_stars_limit: 4
          
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # It is required to fetch all commits to be able to force-push later
          fetch-depth: 0

      - name: Prepare commits to combine, if needed
        # If either this or the previous commit is meaningful, should do nothing.
        # Otherwise, combine the two.
        id: commits_preparer
        run: |
          set -e

          echo 'Desired:' "$DESIRED_COMMIT_MESSAGE"

          # Look at the last two commits to see if they are what we need
          for i in 1 2; do
            echo 'Actual:' && git log -1 --pretty=%B
            if [[ "$(git log -1 --pretty=%B)" != "$DESIRED_COMMIT_MESSAGE" ]]; then
              echo should_commit=false >> "$GITHUB_OUTPUT"
              exit 0  # A meaningful message. Thus, nothing to do further
            fi
            git reset --soft HEAD^
          done

          echo should_commit=true >> "$GITHUB_OUTPUT"

      - name: Combine commits
        if: steps.commits_preparer.outputs.should_commit == 'true'
        uses: EndBug/add-and-commit@latest
        with:
          message: ${{env.DESIRED_COMMIT_MESSAGE}}

          default_author: github_actions

          pathspec_error_handling: exitImmediately

          push: origin main --force
